# @format

version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123
      ME_CONFIG_MONGODB_URL: mongodb://root:root123@mongo:27017

  itsprashant008/docker-nodejs-setup:
    image: itsprashant008/docker-nodejs-setup
    ports:
      - 3000:3000
    environment:
      MONGO_DB_USERNAME: admin
      MONGO_DB_PASSWORD: pass
